# This configmap allows us to switch to the halconfig-marketplace bucket instead of the halconfig bucket; this is currently turned off.
apiVersion: v1
kind: ConfigMap
metadata:
  name: halyard-custom-config
  namespace: spinnaker-operator
data:
  halyard-local.yml: |
    spinnaker:
      config:
        input:
          bucket: halconfig-marketplace
