apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-operator
  namespace: spinnaker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spinnaker-operator
  template:
    metadata:
      labels:
        name: spinnaker-operator
    spec:
      serviceAccountName: spinnaker-operator
      initContainers:
        - 
          name: start-billing
          args:
          - meteringmarketplace
          - register-usage
          - --product-code
          - 3g3248j9dxzytipo7aj4jlwiu
          - --public-key-version
          - "1"
          # image: amazon/aws-cli
          image: 117940112483.dkr.ecr.us-east-1.amazonaws.com/3a387dea-4960-43d1-8539-c26bbc74cae6/cg-3837021117/amazon/aws-cli:1.0.0-latest
      containers:
        - name: spinnaker-operator
          # image: armory/armory-operator:1.0.0
          image: 117940112483.dkr.ecr.us-east-1.amazonaws.com/3a387dea-4960-43d1-8539-c26bbc74cae6/cg-3837021117/armory/armory-operator:1.0.0-latest
          command:
            - spinnaker-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "spinnaker-operator"
        - name: halyard
          # image: armory/halyard-armory:operator-fa2cee7d1fe561cd709894198806f072e6eac1e1
          image: 117940112483.dkr.ecr.us-east-1.amazonaws.com/3a387dea-4960-43d1-8539-c26bbc74cae6/cg-3837021117/armory/halyard-armory:1.0.0-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8064
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8064
            failureThreshold: 20
            periodSeconds: 5
            initialDelaySeconds: 20
          livenessProbe:
            tcpSocket:
              port: 8064
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
          - name: halyard-custom-config
            mountPath: /opt/spinnaker/config/halyard-local.yml
            subPath: halyard-local.yml
      volumes:
      - name: halyard-custom-config
        configMap:
          name: halyard-custom-config