apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-operator
  namespace: spinnaker-operator
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWS_ACCOUNT_ID:role/eks-spinnaker-operator