
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 2.19.9
      artifacts:
        http:
          accounts: []
          enabled: true
      features:
        artifacts: true
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: BUCKET_NAME
      providers:
        kubernetes:
          accounts:
          - name: spinnaker
            onlySpinnakerManaged: true
            providerVersion: V2
            serviceAccount: true
          enabled: true
          primaryAccount: spinnaker
      security:
        uiSecurity:
          overrideBaseUrl: https://spinnaker.domain.com
        apiSecurity:
          overrideBaseUrl: https://spinnaker.domain.com/api/v1
    profiles:
      deck:
        settings-local.js: |
          window.spinnakerSettings.feature.kustomizeEnabled = true;
      front50:
        spinnaker.s3.versioning: false
      gate:
        server:
          servlet:
            context-path: /api/v1
          tomcat:
            httpsServerPort: X-Forwarded-Port
            internalProxies: .*
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
    service-settings:
      clouddriver:
        kubernetes:
          serviceAccountName: clouddriver
      front50:
        kubernetes:
          serviceAccountName: front50
      gate:
        healthEndpoint: /api/v1/health
  expose: {}
