
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  spinnakerConfig:
    config:
      artifacts:
        http:
          accounts: []
          enabled: true
      features:
        artifacts: true
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: BUCKETNAME
      providers:
        kubernetes:
          accounts:
          - name: spinnaker
            onlySpinnakerManaged: true
            providerVersion: V2
            serviceAccount: true
          enabled: true
          primaryAccount: spinnaker
      # security:
      #   apiSecurity:
      #     overrideBaseUrl: https://ENDPOINT/api/v1
      #   uiSecurity:
      #     overrideBaseUrl: https://ENDPOINT
      version: 2.19.9
    profiles:
      clouddriver: {}
      deck:
        settings-local.js: |
          window.spinnakerSettings.feature.kustomizeEnabled = true;
      echo: {}
      fiat: {}
      front50:
        spinnaker.s3.versioning: false
      gate:
        server:
          servlet:
            context-path: /api/v1
          tomcat:
            httpsServerPort: X-Forwarded-Port
            internalProxies: .*
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
      igor: {}
      kayenta: {}
      orca: {}
      rosco: {}
    service-settings:
      clouddriver:
        kubernetes:
          serviceAccountName: clouddriver
      deck: {}
      echo: {}
      fiat: {}
      front50: {}
      gate:
        healthEndpoint: /api/v1/health
      igor: {}
      kayenta: {}
      orca: {}
      rosco: {}